
import java.awt.TextField;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Oanhpv1008
 */
public class BT1CalculateArray extends javax.swing.JFrame {

    long s1 = 0, s2 = 0, s = 0;
    boolean kt1 = false, kt2 = false;
    //Tạo lớp tuyến đoạn chúng

    public class Tuyen extends Thread {

        int td; //lưu tuyến đoạn thứ mấy
        int[] a; //Mảng a cần tính tổnge

        public Tuyen(int td, int[] a) { //Tạo hàm tạo
            this.td = td;
            this.a = a;
        }

        @Override
        public void run() {
            if (td == 1) {//nếu là tuyến 1
                int n = a.length;
                //Tính nữa mảng đầu
                for (int i = 0; i < n / 2; i++) {
                    s1 = s1 + a[i];
                }
                kt1 = true;
            }
            if (td == 2) {////nếu là tuyến 2
                int n = a.length;
                //Tính nữa mảng sau
                for (int i = n / 2; i < n; i++) {
                    s2 = s2 + a[i];
                }
                kt2 = true;
            }
        }
    }

        /**
         * Creates new form Jframe
         */
        public BT1CalculateArray() {
            initComponents();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtArray = new javax.swing.JTextField();
        txtTd1 = new javax.swing.JTextField();
        txtTd2 = new javax.swing.JTextField();
        txtTd = new javax.swing.JTextField();
        txtTinh = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        txtArray.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtArrayActionPerformed(evt);
            }
        });

        txtTd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTd1ActionPerformed(evt);
            }
        });

        txtTinh.setLabel("tinh");
        txtTinh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinhActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtArray, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtTd1, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                        .addComponent(txtTd2)
                        .addComponent(txtTd)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(101, 101, 101)
                            .addComponent(txtTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtArray, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTd2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(txtTinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtArrayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtArrayActionPerformed
        // TODO add your handling code here:
        

    }//GEN-LAST:event_txtArrayActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        // TODO code application logic here
      
    }//GEN-LAST:event_formWindowOpened

    private void txtTd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTd1ActionPerformed

    private void txtTinhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinhActionPerformed
        s1=0;
        s2=0;
        String arrString = txtArray.getText();
        String[] ds = arrString.split("[;]");
        int n = ds.length;
        int[] a = new int[ds.length];
        for (int i = 0; i < n; i++) {
            a[i] = Integer.parseInt(ds[i]);
        }
        for(int i =1 ;i<=2;i++){
            Tuyen tuyen = new Tuyen(i,a);
            tuyen.start();
        }
        while(true){
            System.out.println("Wait....");
            if(kt1 && kt2){
                txtTd1.setText(s1+"");
                txtTd2.setText(s2+"");
                txtTd.setText(""+(s1+s2));
                break;
            }
        }

    }//GEN-LAST:event_txtTinhActionPerformed

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(BT1CalculateArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(BT1CalculateArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(BT1CalculateArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(BT1CalculateArray.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new BT1CalculateArray().setVisible(true);
                }
            });
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField txtArray;
    private javax.swing.JTextField txtTd;
    private javax.swing.JTextField txtTd1;
    private javax.swing.JTextField txtTd2;
    private java.awt.Button txtTinh;
    // End of variables declaration//GEN-END:variables
}

