spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booking247
    username: root
    password: 10082001
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  messages:
    basename: message
logging:
  level:
    sql: debug
server:
  port: 9090