/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.43
 * Generated at: 2022-11-17 01:03:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import bean.UserBean;
import java.util.ArrayList;
import java.lang.reflect.Array;
import java.util.stream.Collectors;
import java.util.Collections;
import java.util.List;
import bean.SachBean;
import bean.LoaiBean;
import bo.SachBo;
import bo.LoaiBo;

public final class htsach_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1666925691726L));
    _jspx_dependants.put("jar:file:/D:/Workspace/Java/JavaSchool/JAVA_advanced/Java_2/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/Java5/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425953470000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("bean.LoaiBean");
    _jspx_imports_classes.add("java.lang.reflect.Array");
    _jspx_imports_classes.add("bo.LoaiBo");
    _jspx_imports_classes.add("bean.SachBean");
    _jspx_imports_classes.add("bean.UserBean");
    _jspx_imports_classes.add("bo.SachBo");
    _jspx_imports_classes.add("java.util.stream.Collectors");
    _jspx_imports_classes.add("java.util.Collections");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");

request.setCharacterEncoding("utf-8");
response.setCharacterEncoding("utf-8");

      out.write("\r\n");
      out.write("<title>Bootstrap Example</title>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css\">\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

	UserBean user = (UserBean) session.getAttribute("dn");
	
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse\">\r\n");
      out.write("\t\t<div class=\"container-fluid\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t<li class=\"active\"><a href=\"#\">Trang chủ</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"GioHang\">Giỏ hàng</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"GioHang\">Thanh toán</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"LichSuMuaHang\">Lịch sử mua hàng</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t");

				if (session.getAttribute("dn") == null) {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"SignUp\"><span class=\"glyphicon glyphicon-user\"></span>\r\n");
      out.write("\t\t\t\t\t\tSign up</a></li>\r\n");
      out.write("\t\t\t\t<li><a href=\"KiemTraDangNhap\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-log-in\"></span> Login</a></li>\r\n");
      out.write("\t\t\t\t");

				} else {
				
      out.write("\r\n");
      out.write("\t\t\t\t<li><a href=\"#\"><span class=\"glyphicon glyphicon-user\"></span>\r\n");
      out.write("\t\t\t\t\t\tXin chào: ");
      out.print(user.getFullName());
      out.write("</a></li>\r\n");
      out.write("\t\t\t\t<li><a data-toggle=\"modal\" data-target=\"#exampleModal\"><span\r\n");
      out.write("\t\t\t\t\t\tclass=\"glyphicon glyphicon-user\"></span> Logout</a></li>\r\n");
      out.write("\t\t\t\t<!-- Modal -->\r\n");
      out.write("\t\t\t\t<div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\"\r\n");
      out.write("\t\t\t\t\trole=\"dialog\" aria-labelledby=\"exampleModalLabel\"\r\n");
      out.write("\t\t\t\t\taria-hidden=\"true\">\r\n");
      out.write("\t\t\t\t\t<div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-header\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h5 class=\"modal-title\" id=\"exampleModalLabel\">Modal title</h5>\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\taria-label=\"Close\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t\t\t</button>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"modal-footer\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<button type=\"button\" class=\"btn btn-secondary\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdata-dismiss=\"modal\">Cancel</button>\r\n");
      out.write("\t\t\t\t\t\t\t\t<a href=\"Logout\" type=\"button\" class=\"btn btn-primary\">OK</a>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t");

				}
				
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t");

	request.setCharacterEncoding("utf-8");
	response.setCharacterEncoding("utf-8");

	List<SachBean> dssach = (List<SachBean>) request.getAttribute("dssach");

	List<LoaiBean> dsloai = (List<LoaiBean>) request.getAttribute("dsloai");
	
      out.write("\r\n");
      out.write("\t<table width=\"100%\" align=\"center\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"20%\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t\t");

					for (LoaiBean l : dsloai) {
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><a href=\"HtSach?ml=");
      out.print(l.getMaloai());
      out.write('"');
      out.write('>');
      out.write(' ');
      out.print(l.getTenloai());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

					}
					
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"60%\" valign=\"top\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<h2>");
      out.print(request.getAttribute("muatc")!=null?"Mua hang thanh cong !":"" );
      out.write("</h2>\r\n");
      out.write("\t\t\t\t<div class=\"container\" style=\"width: 80%\">\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<div id=\"myCarousel\" class=\"carousel slide\" data-ride=\"carousel\">\r\n");
      out.write("\t\t\t\t\t\t<!-- Indicators -->\r\n");
      out.write("\t\t\t\t\t\t<ol class=\"carousel-indicators\">\r\n");
      out.write("\t\t\t\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"0\" class=\"active\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"1\"></li>\r\n");
      out.write("\t\t\t\t\t\t\t<li data-target=\"#myCarousel\" data-slide-to=\"2\"></li>\r\n");
      out.write("\t\t\t\t\t\t</ol>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Wrapper for slides -->\r\n");
      out.write("\t\t\t\t\t\t<div class=\"carousel-inner\">\r\n");
      out.write("\t\t\t\t\t\t");
for(int i=0;i<3;i++) {
							if(i == 0){
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item active\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"https://aphoto.vn/wp-content/uploads/2018/02/anh-chup-dien-thoai-dep.jpg\" style=\"width:100%;height:300px;\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t");
 }else{
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"item\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"https://aphoto.vn/wp-content/uploads/2018/02/anh-dep-chup-va-blend-bang-dien-thoai-7.jpg\" style=\"width:100%;height:300px\">\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t");
}} 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<!-- Left and right controls -->\r\n");
      out.write("\t\t\t\t\t\t<a class=\"left carousel-control\" href=\"#myCarousel\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-slide=\"prev\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-left\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"sr-only\">Previous</span>\r\n");
      out.write("\t\t\t\t\t\t</a> <a class=\"right carousel-control\" href=\"#myCarousel\"\r\n");
      out.write("\t\t\t\t\t\t\tdata-slide=\"next\"> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"glyphicon glyphicon-chevron-right\"></span> <span\r\n");
      out.write("\t\t\t\t\t\t\tclass=\"sr-only\">Next</span>\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<table class=\"table table-hover\">\r\n");
      out.write("\t\t\t\t\t");

					int n = dssach.size();
					for (int i = 0; i < n; i++) {
						SachBean s = dssach.get(i);
					
      out.write("\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"");
      out.print(s.getAnh());
      out.write("\"><br> ");
      out.print(s.getTensach());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<br> ");
      out.print(s.getTacgia());
      out.write(" <br> ");
      out.print(s.getGia());
      out.write(" <br>\r\n");
      out.write("\t\t\t\t\t\t\tSố lượng:");
      out.print(s.getSoluong() );
      out.write("<br>\r\n");
      out.write("\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"ThemGioHang?ms=");
      out.print(s.getMasach());
      out.write("&ts=");
      out.print(s.getTensach());
      out.write("&gia=");
      out.print(s.getGia());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"buynow.jpg\">\r\n");
      out.write("\t\t\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t\t\t");

						i++;
						if (i < n) {
							s = dssach.get(i);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"");
      out.print(s.getAnh());
      out.write("\"><br> ");
      out.print(s.getTensach());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<br> ");
      out.print(s.getTacgia());
      out.write(" <br> ");
      out.print(s.getGia());
      out.write(" <br>\r\n");
      out.write("\t\t\t\t\t\t\tSố lượng:");
      out.print(s.getSoluong() );
      out.write("<br>\r\n");
      out.write("\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"ThemGioHang?ms=");
      out.print(s.getMasach());
      out.write("&ts=");
      out.print(s.getTensach());
      out.write("&gia=");
      out.print(s.getGia());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"buynow.jpg\">\r\n");
      out.write("\t\t\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");

						i++;
						if (i < n) {
							s = dssach.get(i);
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<td><img src=\"");
      out.print(s.getAnh());
      out.write("\"><br> ");
      out.print(s.getTensach());
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<br> ");
      out.print(s.getTacgia());
      out.write(" <br> ");
      out.print(s.getGia());
      out.write(" <br>\r\n");
      out.write("\t\t\t\t\t\t\tSố lượng:");
      out.print(s.getSoluong() );
      out.write("<br>\r\n");
      out.write("\t\t\t\t\t\t\t<a\r\n");
      out.write("\t\t\t\t\t\t\thref=\"ThemGioHang?ms=");
      out.print(s.getMasach());
      out.write("&ts=");
      out.print(s.getTensach());
      out.write("&gia=");
      out.print(s.getGia());
      out.write("\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<img src=\"buynow.jpg\">\r\n");
      out.write("\t\t\t\t\t\t</a></td>\r\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");

					}
					
      out.write("\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"20%\" valign=\"top\">\r\n");
      out.write("\t\t\t\t<form action=\"HtSach\" method=\"get\">\r\n");
      out.write("\t\t\t\t\t<input class=\"form-control\" name=\"txttk\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(request.getParameter("tk") == null ? "" : request.getParameter("tk"));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\tplaceholder=\"Nhap tt\"> <br> <input\r\n");
      out.write("\t\t\t\t\t\tclass=\"btn-primary\" name=\"butt\" type=\"submit\" value=\"Search\">\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"float-end\" style=\"display: grid; justify-content: center;\">\r\n");
      out.write("\t\t<ul class=\"pagination\">\r\n");
      out.write("\t\t\t");

			long totalPages = (long) request.getAttribute("totalPages");
			for (long i = 1; i <= totalPages; i++) {
			
      out.write("\r\n");
      out.write("\t\t\t<li class=\"page-item\"><a href=\"HtSach?page=");
      out.print(i);
      out.write("\"\r\n");
      out.write("\t\t\t\tclass=\"page-link\">");
      out.print(i);
      out.write("</a></li>\r\n");
      out.write("\t\t\t");

			}
			
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
